import { readFileSync } from 'node:fs';
import { validateDesign, FONTS } from './spec.mjs';
import { hash } from './security.mjs';
const j = value => JSON.stringify(value, null, 2);
const schema = value => '\n{% schema %}\n' + j(value) + '\n{% endschema %}';
const label = (id, type = 'text') => ({ type, id, label: id.replaceAll('_', ' ') });
export const locales = {
  nl: { general: { skip: 'Naar inhoud', shop: 'Collectie', cart: 'Winkelmand', search: 'Zoeken', menu: 'Menu', empty: 'Je collectie verschijnt hier zodra er producten zijn.', no_image: 'Afbeelding volgt', sold_out: 'Uitverkocht', add: 'In winkelmand', variant: 'Uitvoering', quantity: 'Aantal', checkout: 'Naar afrekenen', update: 'Bijwerken', remove: 'Verwijderen', total: 'Totaal', empty_cart: 'Je winkelmand is nog leeg.', continue: 'Verder winkelen', about: 'Ons verhaal', contact: 'Contact', results: 'Zoekresultaten', no_results: 'Geen producten gevonden.', send: 'Versturen', email: 'E-mail', name: 'Naam', message: 'Bericht', sent: 'Bedankt! Je bericht is ontvangen.', not_found: 'Deze pagina bestaat niet.', tax: 'Verzending en eventuele belastingen worden berekend bij het afrekenen.', product: 'Product', next: 'Volgende', previous: 'Vorige' } },
  en: { general: { skip: 'Skip to content', shop: 'Collection', cart: 'Cart', search: 'Search', menu: 'Menu', empty: 'Your collection appears here once products are available.', no_image: 'Image coming soon', sold_out: 'Sold out', add: 'Add to cart', variant: 'Option', quantity: 'Quantity', checkout: 'Checkout', update: 'Update cart', remove: 'Remove', total: 'Total', empty_cart: 'Your cart is empty.', continue: 'Continue shopping', about: 'Our story', contact: 'Contact', results: 'Search results', no_results: 'No products found.', send: 'Send message', email: 'Email', name: 'Name', message: 'Message', sent: 'Thank you! Your message has been received.', not_found: 'This page could not be found.', tax: 'Shipping and any taxes are calculated at checkout.', product: 'Product', next: 'Next', previous: 'Previous' } }
};
const pagination = `{% if paginate.pages > 1 %}<nav class="sc-pagination" aria-label="Pagination">{% if paginate.previous %}<a href="{{ paginate.previous.url }}">{{ 'general.previous' | t }}</a>{% endif %}<span>{{ paginate.current_page }} / {{ paginate.pages }}</span>{% if paginate.next %}<a href="{{ paginate.next.url }}">{{ 'general.next' | t }}</a>{% endif %}</nav>{% endif %}`;
const card = `<a class="sc-card" href="{{ product.url }}"><div class="sc-card-media">{% if product.featured_image %}<img src="{{ product.featured_image | image_url: width: 900 }}" alt="{{ product.title | escape }}" loading="lazy" width="900" height="1100">{% else %}<span>{{ 'general.no_image' | t }}</span>{% endif %}{% unless product.available %}<span class="sc-stock">{{ 'general.sold_out' | t }}</span>{% endunless %}</div><div class="sc-card-meta"><h3>{{ product.title | escape }}</h3><span>{{ product.price | money_with_currency | strip_html }}</span></div></a>`;
const image = `<div class="sc-visual">{% if section.settings.image != blank %}<img src="{{ section.settings.image | image_url: width: 1800 }}" alt="{{ section.settings.image_alt | escape }}" width="1200" height="1400" loading="eager">{% elsif section.settings.image_url != blank %}<img src="{{ section.settings.image_url | escape }}" alt="{{ section.settings.image_alt | escape }}" width="1200" height="1400" loading="eager">{% endif %}</div>`;
const heading = `<p class="sc-kicker">{{ section.settings.kicker | escape }}</p><h2>{{ section.settings.title | escape | newline_to_br }}</h2><p class="sc-body">{{ section.settings.text | escape | newline_to_br }}</p>`;
const button = `{% if section.settings.button_label != blank %}<a class="sc-button" href="{{ section.settings.button_url | default: routes.all_products_collection_url }}">{{ section.settings.button_label | escape }}<span aria-hidden="true">↗</span></a>{% endif %}`;
const common = [label('kicker'), label('title', 'textarea'), label('text', 'textarea'), label('button_label'), label('button_url', 'url'), { type: 'image_picker', id: 'image', label: 'Image' }, label('image_url', 'url'), label('image_alt'), { type: 'select', id: 'layout', label: 'Layout', options: ['split', 'full', 'center', 'editorial'].map(value => ({ value, label: value })), default: 'split' }];
const templates = {
  hero: `<section class="sc-hero sc-hero--{{ section.settings.layout }}"><div class="sc-hero-copy"><p class="sc-kicker">{{ section.settings.kicker | escape }}</p><h1>{{ section.settings.title | escape | newline_to_br }}</h1><p class="sc-body">{{ section.settings.text | escape | newline_to_br }}</p>${button}</div>${image}</section>`,
  story: `<section class="sc-section sc-story sc-story--{{ section.settings.layout }}">${image}<div>${heading}${button}</div></section>`,
  statement: `<section class="sc-section sc-statement">${heading}${button}</section>`,
  products: `<section class="sc-section"><div class="sc-section-head"><div>${heading}</div><a class="sc-text-link" href="{{ routes.all_products_collection_url }}">{{ 'general.shop' | t }} ↗</a></div><div class="sc-grid">{% if section.blocks.size > 0 %}{% for block in section.blocks %}{% assign product = block.settings.product %}{% if product != blank %}<div {{ block.shopify_attributes }}>${card}</div>{% endif %}{% endfor %}{% else %}{% for product in collections.all.products limit: 8 %}${card}{% else %}<div class="sc-empty"><span aria-hidden="true">＋</span><p>{{ 'general.empty' | t }}</p></div>{% endfor %}{% endif %}</div></section>`,
  features: `<section class="sc-section">${heading}<div class="sc-features">{% for block in section.blocks %}<article {{ block.shopify_attributes }}><span class="sc-kicker">0{{ forloop.index }}</span><h3>{{ block.settings.title | escape }}</h3><p>{{ block.settings.text | escape | newline_to_br }}</p></article>{% endfor %}</div></section>`,
  faq: `<section class="sc-section sc-faq"><div>${heading}</div><div>{% for block in section.blocks %}<details {{ block.shopify_attributes }}><summary>{{ block.settings.title | escape }}</summary><p>{{ block.settings.text | escape | newline_to_br }}</p></details>{% endfor %}</div></section>`,
  collections: `<section class="sc-section">${heading}<div class="sc-grid">{% for block in section.blocks %}<a class="sc-collection-card" href="{{ block.settings.url }}" {{ block.shopify_attributes }}>{% if block.settings.image_url != blank %}<img src="{{ block.settings.image_url | escape }}" alt="{{ block.settings.title | escape }}" width="900" height="1000" loading="lazy">{% endif %}<h3>{{ block.settings.title | escape }} ↗</h3><p>{{ block.settings.text | escape }}</p></a>{% endfor %}</div></section>`
};
export function compileTheme(raw) {
  const d = validateDesign(raw), t = d.tokens, files = {}, current = { brand: d.brand, announcement: d.announcement, description: d.description, seo_title: d.seo.title, seo_description: d.seo.description };
  const settingsSchema = [label('brand'), label('announcement'), label('description', 'textarea'), label('seo_title'), label('seo_description', 'textarea')];
  let nav = '';
  d.nav.forEach((n, i) => { current[`nav_label_${i}`] = n.label; current[`nav_url_${i}`] = n.url; settingsSchema.push(label(`nav_label_${i}`), label(`nav_url_${i}`, 'url')); nav += `<a href="{{ settings.nav_url_${i} }}">{{ settings.nav_label_${i} | escape }}</a>`; });
  const css = readFileSync(new URL('./storefront.css', import.meta.url), 'utf8');
  const js = readFileSync(new URL('./storefront.js', import.meta.url), 'utf8');
  files['layout/theme.liquid'] = `<!doctype html><html lang="${d.language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ page_title | default: settings.seo_title | escape }}</title><meta name="description" content="{{ page_description | default: settings.seo_description | escape }}"><link rel="canonical" href="{{ canonical_url }}">{{ content_for_header }}<style>:root{--sc-bg:${t.background};--sc-ink:${t.text};--sc-surface:${t.surface};--sc-accent:${t.accent};--sc-accent-ink:${t.accentText};--sc-muted:${t.muted};--sc-heading:${FONTS[t.headingFont]};--sc-radius:${t.radius}px;--sc-max:${t.maxWidth}px;--sc-space:${t.spacing}px;--sc-scale:${t.headingScale}px}${css}</style></head><body><a class="sc-skip" href="#MainContent">{{ 'general.skip' | t }}</a>{% if settings.announcement != blank %}<div class="sc-announcement">{{ settings.announcement | escape }}</div>{% endif %}<header class="sc-header"><a class="sc-brand" href="{{ routes.root_url }}">{{ settings.brand | escape }}</a><nav aria-label="{{ 'general.menu' | t }}">${nav}</nav><div class="sc-header-actions"><a href="{{ routes.search_url }}">{{ 'general.search' | t }}</a><a href="{{ routes.cart_url }}">{{ 'general.cart' | t }} <span class="sc-cart-count">{{ cart.item_count }}</span></a></div><details class="sc-mobile-menu"><summary>{{ 'general.menu' | t }} ＋</summary><nav>${nav}<a href="{{ routes.search_url }}">{{ 'general.search' | t }}</a></nav></details></header><main id="MainContent" tabindex="-1">{{ content_for_layout }}</main><footer class="sc-footer"><div><a class="sc-brand" href="{{ routes.root_url }}">{{ settings.brand | escape }}</a><p>{{ settings.description | escape }}</p></div><nav><a href="{{ routes.all_products_collection_url }}">{{ 'general.shop' | t }}</a><a href="/?view=about">{{ 'general.about' | t }}</a><a href="/?view=contact">{{ 'general.contact' | t }}</a>{% for policy in shop.policies %}{% if policy.body != blank %}<a href="{{ policy.url }}">{{ policy.title | escape }}</a>{% endif %}{% endfor %}</nav><span>© {{ 'now' | date: '%Y' }} {{ settings.brand | escape }}</span></footer><script>${js}</script></body></html>`;
  const sections = {};
  for (const s of d.sections) {
    const blocks = {}, order = [];
    if (s.type === 'products') s.productHandles.forEach((handle, i) => { blocks['item_' + i] = { type: 'product', settings: { product: handle } }; order.push('item_' + i); });
    else s.items.forEach((item, i) => { blocks['item_' + i] = { type: 'item', settings: { title: item.title, text: item.text, image_url: item.image, url: item.url } }; order.push('item_' + i); });
    sections[s.id] = { type: 'sc-' + s.type, settings: { kicker: s.kicker, title: s.title, text: s.text, button_label: s.buttonLabel, button_url: s.buttonUrl, image_url: s.image, image_alt: s.imageAlt, layout: s.layout }, blocks, block_order: order };
  }
  for (const [type, markup] of Object.entries(templates)) files[`sections/sc-${type}.liquid`] = markup + schema({ name: 'StoreCrew ' + type, settings: common, max_blocks: 12, blocks: type === 'products' ? [{ type: 'product', name: 'Product', settings: [{ type: 'product', id: 'product', label: 'Product' }] }] : [{ type: 'item', name: 'Item', settings: [label('title'), label('text', 'textarea'), label('image_url', 'url'), label('url', 'url')] }], presets: [{ name: 'StoreCrew ' + type }] });
  files['templates/index.json'] = j({ sections, order: Object.keys(sections) });
  const product = `<section class="sc-section sc-product">{% if product != blank %}<div class="sc-gallery">{% for image in product.images %}<img src="{{ image | image_url: width: 1200 }}" alt="{{ product.title | escape }}" width="1200" height="1400" loading="{% if forloop.first %}eager{% else %}lazy{% endif %}">{% else %}<div class="sc-empty">{{ 'general.no_image' | t }}</div>{% endfor %}</div><div class="sc-product-info"><p class="sc-kicker">{{ product.vendor | escape }}</p><h1>{{ product.title | escape }}</h1><p class="sc-price" data-price>{{ product.selected_or_first_available_variant.price | money_with_currency | strip_html }}</p><p class="sc-body">{{ product.description | strip_html | escape | newline_to_br }}</p>{% form 'product', product %}<label for="VariantSelect">{{ 'general.variant' | t }}</label><select name="id" id="VariantSelect" data-variant>{% for variant in product.variants %}<option value="{{ variant.id }}" data-price="{{ variant.price | money_with_currency | strip_html | escape }}" data-available="{{ variant.available }}" {% if variant == product.selected_or_first_available_variant %}selected{% endif %} {% unless variant.available %}disabled{% endunless %}>{{ variant.title | escape }} — {{ variant.price | money_with_currency | strip_html }}{% unless variant.available %} · {{ 'general.sold_out' | t }}{% endunless %}</option>{% endfor %}</select><label for="Quantity">{{ 'general.quantity' | t }}</label><input id="Quantity" name="quantity" type="number" min="1" max="99" value="1"><button class="sc-button" data-add data-label="{{ 'general.add' | t }}" data-sold="{{ 'general.sold_out' | t }}" {% unless product.available %}disabled{% endunless %}>{% if product.available %}{{ 'general.add' | t }}{% else %}{{ 'general.sold_out' | t }}{% endif %}</button>{% endform %}<p class="sc-small">{{ 'general.tax' | t }}</p></div>{% else %}<div class="sc-empty">{{ 'general.empty' | t }}</div>{% endif %}</section>`;
  const collection = `<section class="sc-section"><p class="sc-kicker">{{ 'general.shop' | t }}</p><h1>{{ collection.title | escape }}</h1><p class="sc-body">{{ collection.description | strip_html | escape }}</p>{% paginate collection.products by 24 %}<div class="sc-grid">{% for product in collection.products %}${card}{% else %}<p>{{ 'general.empty' | t }}</p>{% endfor %}</div><div class="sc-pagination">${pagination}</div>{% endpaginate %}</section>`;
  const cart = `<section class="sc-section sc-cart"><h1>{{ 'general.cart' | t }}</h1>{% if cart.item_count > 0 %}<form action="{{ routes.cart_url }}" method="post" id="CartForm">{% for item in cart.items %}<div class="sc-cart-line"><a href="{{ item.url }}">{{ item.title | escape }}</a><label>{{ 'general.quantity' | t }}<input name="updates[]" type="number" min="0" max="99" value="{{ item.quantity }}" data-variant-id="{{ item.variant_id }}"></label><strong>{{ item.final_line_price | money_with_currency | strip_html }}</strong></div>{% endfor %}<p class="sc-price">{{ 'general.total' | t }}: {{ cart.total_price | money_with_currency | strip_html }}</p><p class="sc-small">{{ 'general.tax' | t }}</p><button class="sc-button sc-secondary" name="update">{{ 'general.update' | t }}</button><button class="sc-button" name="checkout">{{ 'general.checkout' | t }}</button></form>{% else %}<p>{{ 'general.empty_cart' | t }}</p><a class="sc-button" href="{{ routes.all_products_collection_url }}">{{ 'general.continue' | t }}</a>{% endif %}</section>`;
  const aboutStory = d.sections.find(s => s.type === 'story');
  current.about_title = aboutStory?.title || locales[d.language].general.about; current.about_text = aboutStory?.text || d.description;
  settingsSchema.push(label('about_title', 'textarea'), label('about_text', 'textarea'));
  const page = `<section class="sc-section sc-prose">{% if page.handle == 'about' %}<h1>{{ settings.about_title | escape | newline_to_br }}</h1><p>{{ settings.about_text | escape | newline_to_br }}</p>{% else %}<h1>{{ page.title | escape }}</h1>{{ page.content }}{% endif %}</section>`;
  const about = `<section class="sc-section sc-prose"><h1>{{ settings.about_title | escape | newline_to_br }}</h1><p>{{ settings.about_text | escape | newline_to_br }}</p></section>`;
  const contact = `<section class="sc-section sc-prose"><h1>{{ 'general.contact' | t }}</h1>{% form 'contact' %}{% if form.posted_successfully? %}<p>{{ 'general.sent' | t }}</p>{% endif %}{{ form.errors | default_errors }}<label for="ContactName">{{ 'general.name' | t }}</label><input id="ContactName" name="contact[name]" autocomplete="name" required><label for="ContactEmail">{{ 'general.email' | t }}</label><input id="ContactEmail" name="contact[email]" type="email" autocomplete="email" required><label for="ContactBody">{{ 'general.message' | t }}</label><textarea id="ContactBody" name="contact[body]" rows="6" required></textarea><button class="sc-button">{{ 'general.send' | t }}</button>{% endform %}</section>`;
  const search = `<section class="sc-section"><h1>{{ 'general.search' | t }}</h1><form action="{{ routes.search_url }}" method="get" class="sc-search-form"><label for="SearchInput">{{ 'general.search' | t }}</label><input id="SearchInput" name="q" type="search" value="{{ search.terms | escape }}"><input type="hidden" name="type" value="product"><button class="sc-button">{{ 'general.search' | t }}</button></form>{% if search.performed %}{% paginate search.results by 24 %}<div class="sc-grid">{% for product in search.results %}${card}{% else %}<p>{{ 'general.no_results' | t }}</p>{% endfor %}</div>${pagination}{% endpaginate %}{% endif %}</section>`;
  const missing = `<section class="sc-section"><h1>{{ 'general.not_found' | t }}</h1><a class="sc-button" href="{{ routes.all_products_collection_url }}">{{ 'general.continue' | t }}</a></section>`;
  for (const [name, markup] of Object.entries({ product, collection, cart, page, 'page.contact': contact, 'index.about': about, 'index.contact': contact, search, '404': missing })) { const type = 'sc-main-' + name.replace('.', '-'); files[`sections/${type}.liquid`] = markup + schema({ name: name === 'page.contact' ? 'Contact' : name, settings: [] }); files[`templates/${name}.json`] = j({ sections: { main: { type, settings: {} } }, order: ['main'] }); }
  files['config/settings_schema.json'] = j([{ name: 'theme_info', theme_name: 'StoreCrew Studio', theme_author: 'StoreCrew', theme_version: '2.0.0', theme_documentation_url: 'https://github.com/bouwendijk/Ai-agent/tree/storecrew-studio-v1/storecrew', theme_support_url: 'https://github.com/bouwendijk/Ai-agent' }, { name: 'StoreCrew', settings: settingsSchema }]);
  files['config/settings_data.json'] = j({ current, presets: {} });
  files['locales/' + d.language + '.default.json'] = j(locales[d.language]);
  files['locales/' + (d.language === 'en' ? 'nl' : 'en') + '.json'] = j(locales[d.language === 'en' ? 'nl' : 'en']);
  return { files, digest: hash(files), design: d };
}
